language: python
matrix:
    include:
        - python: 2.7
        - python: 3.6

install:
  # install TensorFlow (CPU version).
  - pip install soundfile
  - pip install -e .

# command to run tests
script:
  - nosetests --nologcapture